name: Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: gcc
      run: gcc -dM -march=native -E - < /dev/null | egrep "AVX" | sort
    - name: gcc-no512
      run: gcc -dM -march=native -mno-avx512f -E - < /dev/null | egrep "AVX" | sort
    - name: lscpu
      run: lscpu
    - name: benchmark
      run: for i in {1..30}; do time ./statistics > /dev/null; done
