name: Benchmark

on:
  push:
    branches: [ "main", "double_avx" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: lscpu
      run: lscpu
    - name: make_avx2
      run: make 
    - name: benchmark_avx2
      run: make benchmark
    - name: test_avx2
      run: make test  
    - name: make_avx512
      run: make clean; make AVX512=
    - name: benchmark_avx512
      run: make benchmark
    - name: test_avx512
      run: make test
