name: Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: lscpu
      run: lscpu
    - name: benchmark
      run: for i in {1..30}; do time ./statistics > /dev/null; done
