name: Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: lscpu
      run: lscpu
    - name: make_avx2
      run: make 
    - name: benchmark_avx2
      run: make benchmark
    - name: test_avx2
      run: make test  
    - name: make_avx512
      run: lscpu | grep avx512 > /dev/null  && make clean all USE_AVX=avx512 || echo "No AVX512 supported" 
    - name: benchmark_avx512
      run: lscpu | grep avx512 > /dev/null  && make benchmark || echo "No AVX512 supported"
    - name: test_avx512
      run:  lscpu | grep avx512 > /dev/null  && make test || echo "No AVX512 supported"
